config/routes.rb
Blocmetrics::Application.routes.draw do
  resources :events
  match 'events' => "events#index", via: :options

  root to: "welcome#index"
  get 'get_started' => 'welcome#get_started', path: 'get-started'

end

app/models/event.rb
class Event < ActiveRecord::Base
	self.inheritance_column = nil

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_filter :set_headers
  skip_before_action :verify_authenticity_token

  # GET /events
  # GET /events.json
  def index
    #binding.pry
    @events = Event.all
    @events_type = @events.where(type: "click")
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    #binding.pry
    @event = Event.new(event_params)
    @event.ip_address = request.env["REMOTE_HOST"]
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private

    def set_headers
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Expose-Headers'] = 'ETag'
      headers['Access-Control-Allow-Methods'] = 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
      headers['Access-Control-Allow-Headers'] = '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match'
      headers['Access-Control-Max-Age'] = '1728000'
    end

    def permission_denied_error
      error(403, 'Permission Denied!')
    end

    def error(status, message = 'Something went wrong')
      response = {
        response_type: "ERROR", 
        message: message
      }
      render json: response.to_json, status: status
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:web_property_id, :type, :ip_address, :location)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def get_started
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :web_property_id %><br>
    <%= f.number_field :web_property_id %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :ip_address %><br>
    <%= f.text_field :ip_address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="row">
  <h1>Events Happening Each Day</h1>
  <canvas id="myChart" width="500" height="400"></canvas>

  <h1>Clicks Happening Each Day</h1>
  <canvas id="myBarChart" width="500" height="400"></canvas>

  <h1>Click Locations</h1>
  <% @events_type.each do |e| %>
    <p><%= e.location %> on <%= e.created_at.strftime("%b %d, %Y") %></p>
  <% end %>
  <h1>All Events</h1>
  <table>
    <thead>
      <tr>
        <th>Web property</th>
        <th>Type</th>
        <th>Ip address</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.web_property_id %></td>
          <td><%= event.type %></td>
          <td><%= event.ip_address %></td>
          <td><%= event.location %></td>
          <td><%= link_to 'Show', event %></td>
          <td><%= link_to 'Edit', edit_event_path(event) %></td>
          <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <!-- Data for line graph data showing all events by day --> 
  <div id="value-data" class="hidden">
    <%= @events.count(group: "DATE(created_at)").values %>
  </div>
  <div id="value-label" class="hidden">
    <%= @events.count(group: "DATE(created_at)").keys.to_json %>

    $.ajax("/blocmetrics/myurl")
  </div>

  <!-- Data for bar graph showing all clicks by day --> 
  <div id="count" class="hidden">
    <%= @events.where(type: "click").count(group: "DATE(created_at)").values %>
  </div>
  <div id="count-date" class="hidden">
    <%= @events.where(type: "click").count(group: "DATE(created_at)").keys.to_json %>
  </div>

    


  <%= link_to 'New Event', new_event_path %>

</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Web property:</strong>
  <%= @event.web_property_id %>
</p>

<p>
  <strong>Type:</strong>
  <%= @event.type %>
</p>

<p>
  <strong>Ip address:</strong>
  <%= @event.ip_address %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/_nav.html.erb
<% if current_page?(root_path) %>
<% else %>
  <nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
      <li class="name">
        <h1><a href="#">Web Analytics API Tracking Tool</a></h1>
      </li>
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        
      </ul>

      <!-- Left Nav Section -->
      <ul class="left">
        <li class="<%= "nav #{'active' if current_page?(root_path)}" %>"><%= link_to "Home", root_path %></li>
        <li class="<%= "nav #{'active' if current_page?(get_started_path)}" %>"><%= link_to "Get Started", get_started_path %></li>
        <li class="<%= "nav #{'active' if current_page?(events_path)}" %>"><%= link_to "Events", events_path %></li>
      </ul>
    </section>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "API Tracking Service and Reporting Tool" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  	<%= render partial: 'layouts/nav' %>

    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/welcome/get_started.html.erb
<div id="home-intro">
	<div class="row">
		<h1>Web Analytics API Tracking Tool</h1>
		<h3>Add a little javascript snippet to your website and gather data about how people use your site.</h3>
	</div>
</div>

<div id="instructions">
	<div class="row">
		<div class="small-12 medium-6 medium-centered columns">
			<%= link_to "View Updated Instructions on Github", "https://github.com/flores8/blocmetrics#getting-started", class: "button expand" %>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<main id="cd-main-content">
	<section id="cd-intro">
		<h1>Web Analytics API Tracking Tool</h1>

		<header class="cd-header">
			<div id="cd-logo"><%= link_to "Get Started", get_started_path %></div>
			<%= link_to raw("View Events <span></span>"), events_path, class: "cd-menu-trigger" %>
		</header>
		<div class="cd-blurred-bg"></div>
	</section> <!-- cd-intro -->
</main>


<!-- 
<script>
$.ajax("http://blocmetrics.tracking.com:3000", "pageview", current_user.ip)
</script>
-->